version: '3'
services:
  database:
    image: mysql:8
    restart: always
    container_name: meu-mysql
    environment:
      MYSQL_DATABASE: 'clientes'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db2:/var/lib/mysql

volumes:
  mysql-db2: